###POST cadastrar indice
POST http://localhost:3000/indice
Content-Type: application/json

{
    "indice":"i_pessoas"
}

###POST cadastrar documento no indice
POST http://localhost:3000/document?indice=i_pessoas
Content-Type: application/json

{
    "nome":"Alan",
    "sobrenome":"Ramalho",
    "idade": "27"
}

###GET buscar documento do indice
GET http://localhost:3000/document?indice=i_pessoas&id=MLdZOo4BSW5lx05U1np1
Content-Type: application/json